name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create env file
      run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.production
    - name: Build the Docker image
      run: |
        IMAGE_TAG=taijustin/twitter-api:$(date +%s)
        docker build --progress=plain -t $IMAGE_TAG -f Dockerfile .
        echo "::set-output name=image_tag::$IMAGE_TAG"
      id: build
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Push the Docker image
      run: docker push ${{ steps.build.outputs.image_tag }}
